// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-service-categories.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_service_categories_default = defineTool({
  name: "list_service_categories",
  title: "List service categories",
  description: "List all Renovivo renovation service categories (kitchen, bathroom, painting, flooring, etc.).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("service_categories").select("id, name, slug, description, icon").order("name");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { categories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-service-prices.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_service_prices_default = defineTool2({
  name: "list_service_prices",
  title: "List service prices",
  description: "List Renovivo service prices in BGN. Optionally filter by category_id (UUID from list_service_categories).",
  inputSchema: {
    category_id: z.string().uuid().optional().describe("Category UUID to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("service_prices").select(
      "id, category_id, service_name, price_min, price_max, price_text, unit, includes_materials, notes"
    ).order("service_name");
    if (category_id) q = q.eq("category_id", category_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { prices: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "List published Renovivo blog posts about renovation, design, and construction tips.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).optional().describe("Max posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("blog_posts").select("id, title, slug, excerpt, category, tags, author, reading_time, created_at").eq("is_published", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-inspection-request.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_inspection_request_default = defineTool4({
  name: "create_inspection_request",
  title: "Request a site inspection",
  description: "Submit a Renovivo site-inspection / quote request. Renovivo will contact the client to arrange a visit.",
  inputSchema: {
    client_name: z3.string().trim().min(2).max(200).describe("Full name of the client."),
    client_phone: z3.string().trim().min(5).max(50).describe("Contact phone number."),
    client_email: z3.string().email().optional().describe("Optional contact email."),
    address: z3.string().trim().min(3).max(500).describe("Address of the property to inspect."),
    preferred_datetime: z3.string().optional().describe("Preferred date/time for the visit, e.g. '2026-08-01 10:00'."),
    notes: z3.string().max(2e3).optional().describe("Notes about scope / rooms / condition.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("inspection_requests").insert({
      client_name: input.client_name,
      client_phone: input.client_phone,
      client_email: input.client_email ?? ctx.getUserEmail() ?? null,
      address: input.address,
      preferred_datetime: input.preferred_datetime ?? null,
      notes: input.notes ?? null
    }).select("id, created_at, status").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: `Inspection request submitted. Reference: ${data.id} (status: ${data.status}).`
        }
      ],
      structuredContent: { request: data }
    };
  }
});

// src/lib/mcp/tools/list-inspection-requests.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_inspection_requests_default = defineTool5({
  name: "list_inspection_requests",
  title: "List inspection requests (admin)",
  description: "List submitted site-inspection requests. Only Renovivo admins can read them; other users get an empty list from RLS.",
  inputSchema: {
    status: z4.string().optional().describe("Optional status filter (e.g. 'new')."),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser5(ctx).from("inspection_requests").select("id, client_name, client_phone, client_email, address, preferred_datetime, notes, status, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { requests: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dvshtyyyvjxoydoxmebr";
var mcp_default = defineMcp({
  name: "renovivo-mcp",
  title: "Renovivo",
  version: "0.1.0",
  instructions: "Tools for Renovivo \u2014 a renovation services company in Bulgaria. Read service categories and prices (BGN), read blog posts, and submit or (for admins) list site-inspection requests. All tools act as the signed-in Renovivo user and respect row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_service_categories_default,
    list_service_prices_default,
    list_blog_posts_default,
    create_inspection_request_default,
    list_inspection_requests_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
